2005-07-25 Angus Leeming <leeeming@lyx.org>
* dt2dv.c: Enable to handle .dvi files containing strings longer than 1024 chars.

* Makefile: enable the to work out of the box on both *nix and Windows machines
  under the MinSYS environment.

* man2ps: build fixes

See https://marc.info/?l=lyx-devel&m=115228143031699

diff --git a/3rdparty/dtl/man2ps b/3rdparty/dtl/man2ps
--- a/3rdparty/dtl/man2ps
+++ b/3rdparty/dtl/man2ps
@@ -25,16 +25,16 @@ case `basename $0` in
 esac
 
 # We can use either GNU groff or Sun Solaris troff + dpost
-if [ -x /usr/local/bin/groff ]
+if [ which groff > /dev/null ]
 then	# GNU groff
 	TROFF="groff $FORMAT"
 	TROFF2PS="cat"
-elif [ -x /usr/lib/lp/postscript/dpost ]
++elif [ which dpost > /dev/null ]
 then	# Solaris 2.1
 	TROFF="troff $FORMAT"
 	TROFF2PS="/usr/lib/lp/postscript/dpost"
 else
-	echo "Cannot find troff-to-PostScript filter"
++	echo "Cannot find troff-to-PostScript filter" >&2
 	exit 1
 fi
 
