Execute lyx2lyx unit test when running tests
Actually lyx2lyx has a tiny unit test. Add it to the autotools test machinery
and fix it: Since nobody knew about it the test was of course broken.

diff --git a/lib/lyx2lyx/Makefile.am b/lib/lyx2lyx/Makefile.am
--- a/lib/lyx2lyx/Makefile.am
+++ b/lib/lyx2lyx/Makefile.am
@@ -38,3 +38,14 @@ dist_lyx2lyx_PYTHON = \
 
 install-data-hook:
 	$(CHMOD) 755 $(DESTDIR)$(lyx2lyxdir)/lyx2lyx
+
+alltests: check alltests-recursive
+
+alltests-recursive:
+	@$(PYTHON) "$(srcdir)/test_parser_tools.py"; \
+	if test $$? -eq 0; then \
+		echo -e "=====================\nlyx2lyx tests passed.\n====================="; \
+	else \
+		echo -e "=====================\nlyx2lyx tests failed.\n====================="; \
+	fi
+
