#10762 open lyx pipe only once to read the answer

diff --git a/development/MacOSX/lyxeditor b/development/MacOSX/lyxeditor
--- a/development/MacOSX/lyxeditor
+++ b/development/MacOSX/lyxeditor
@@ -87,9 +87,9 @@ if [ -n "$LYXPIPE" -a -p "$LYXPIPE".in ]; then
 	MAC_LYXPIPE_CONTENTS="LYXCMD:macdvix:server-goto-file-row:$file $2"
 	# echo "$MAC_LYXPIPE_CONTENTS"
 	echo "$MAC_LYXPIPE_CONTENTS" > "${LYXPIPE}".in || { echo "Cannot write to lyxpipe." ; exit 2 ; }
-	while read line < "${LYXPIPE}".out ; do
+	while read line ; do
 		echo LyX said: $line
-	done || { echo "Cannot read from lyxpipe." ; exit 2 ; }
+	done < "${LYXPIPE}".out || { echo "Cannot read from lyxpipe." ; exit 2 ; }
 else
 	echo "Our best guess sets lyxpipe as ${LYXPIPE}"
 	echo "But the lyxpipe could not be found."
