Remove layout and tex2lyx tests from make check
These tests need a built and configured LyX, so they do not work in the
distcheck target. They can now be called with make alltests.

diff --git a/src/Makefile.am b/src/Makefile.am
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -668,9 +668,19 @@ endif
 EXTRA_DIST += \
 	tests/test_layout
 
+alltests: check alltests-recursive
 
-TESTS = \
-	tests/test_layout
+alltests-recursive: check_layout
+	@srcdir=$(srcdir) $(srcdir)/tests/test_layout; \
+	if test $$? -eq 0; then \
+		echo -e "====================\nlayout tests passed.\n===================="; \
+	else \
+		echo -e "====================\nlayout tests failed.\n===================="; \
+	fi
+	cd tex2lyx; $(MAKE) alltests-recursive
+
+updatetests:
+	cd tex2lyx; $(MAKE) updatetests
 
 check_PROGRAMS = \
 	check_layout
@@ -699,3 +709,4 @@ check_layout_SOURCES = \
 	support/tests/boost.cpp \
 	support/tests/dummy_functions.cpp
 
+.PHONY: alltests alltests-recursive updatetests
diff --git a/src/tex2lyx/Makefile.am b/src/tex2lyx/Makefile.am
--- a/src/tex2lyx/Makefile.am
+++ b/src/tex2lyx/Makefile.am
@@ -53,7 +53,16 @@ TEST_RESULTS = \
 	test/verbatim.lyx.lyx \
 	test/XeTeX-polyglossia.lyx.lyx
 
-TESTS = test/runtests.py
+alltests: check alltests-recursive
+
+alltests-recursive: tex2lyx
+	@$(PYTHON) "$(srcdir)/test/runtests.py"; \
+	if test $$? -eq 0; then \
+		echo -e "=====================\ntex2lyx tests passed.\n====================="; \
+	else \
+		echo -e "=====================\ntex2lyx tests failed.\n====================="; \
+	fi
+
 updatetests: tex2lyx
 	$(PYTHON) "$(srcdir)/test/runtests.py" ./tex2lyx "$(top_srcdir)/lib/scripts" "$(srcdir)/test"
 
@@ -107,3 +116,5 @@ tex2lyx_LDADD = \
 if INSTALL_MACOSX
 tex2lyx_LDFLAGS = -framework AppKit
 endif
+
+.PHONY: alltests alltests-recursive updatetests
